const ROUTES = {
  HOME: "/",
  DASHBOARD_HOME: "/dashboard",
  DASHBOARD_BOARDS: "/dashboard/board",
  DASHBOARD_BOARDS_CREATE: "/dashboard/board/create",
  DASHBOARD_BOARDS_EDIT: "/dashboard/board/edit",
  DASHBOARD_BOARDS_EDIT_BOARD: "/dashboard/board/edit-board",
  DASHBOARD_BOARDS_DELETE: "/dashboard/board/delete",
  DASHBOARD_POSTS: "/dashboard/posts",
  DASHBOARD_POSTS_CREATE: "/dashboard/posts/create",
  DASHBOARD_POSTS_EDIT: "/dashboard/posts/edit",
  DASHBOARD_POSTS_VIEW: "/dashboard/posts/view",
  DASHBOARD_POSTS_VOTERS: "/dashboard/posts/voters",
  DASHBOARD_POSTS_IMPORT: "/dashboard/posts/import",
  DASHBOARD_STATUS: "/dashboard/status",
  DASHBOARD_STATUS_ADD: "/dashboard/status/add",
  DASHBOARD_STATUS_EDIT: "/dashboard/status/edit",
  DASHBOARD_TAGS: "/dashboard/tags",
  DASHBOARD_TAGS_ADD: "/dashboard/tags/add",
  DASHBOARD_TAGS_EDIT: "/dashboard/tags/edit",
  DASHBOARD_TAGS_REPLACE: "/dashboard/tags/replace",
  DASHBOARD_ACTIVITY: "/dashboard/activity",
  DASHBOARD_USERS: "/dashboard/users",
  DASHBOARD_USERS_DETAILS: "/dashboard/users/details",
  DASHBOARD_USERS_SEGMENTS: "/dashboard/users/segments",
  DASHBOARD_USERS_SEGMENTS_ADD: "/dashboard/users/segments/add",
  DASHBOARD_USERS_SEGMENTS_EDIT: "/dashboard/users/segments/edit",
  DASHBOARD_CHANGELOG: "/dashboard/changelog",
  DASHBOARD_CHANGELOG_ADD: "/dashboard/changelog/add",
  DASHBOARD_CHANGELOG_EDIT: "/dashboard/changelog/edit",
  DASHBOARD_CHANGELOG_LABELS: "/dashboard/changelog/labels",
  DASHBOARD_CHANGELOG_SETTINGS: "/dashboard/changelog/settings",
  DASHBOARD_CHANGELOG_SETTINGS_GENERAL: "/dashboard/changelog/settings/general",
  DASHBOARD_CHANGELOG_LABELS_ADD: "/dashboard/changelog/labels/add",
  DASHBOARD_CHANGELOG_LABELS_EDIT: "/dashboard/changelog/labels/edit",
  DASHBOARD_SETTINGS: "/dashboard/settings",
  DASHBOARD_SETTINGS_APEARANCE: "/dashboard/settings/apearance",
  DASHBOARD_INTEGRATION: "/dashboard/integration",
  DASHBOARD_SETTINGS_DOMAIN: "/dashboard/settings/domain",
  DASHBOARD_SETTINGS_SSO: "/dashboard/settings/sso",
  DASHBOARD_SETTINGS_EMAIL: "/dashboard/settings/email",
  DASHBOARD_SETTINGS_APPEARANCE: "/dashboard/settings/appearance",
  CLIENT_HOME: "/client",
  CLIENT_WORKSPACES: "/client/workspaces",
  CLIENT_WORKSPACES_EDIT: "/client/workspaces/edit",
};

export default ROUTES;
