const ROUTES = {
  HOME: "/",
  DASHBOARD_HOME: "/dashboard",
  DASHBOARD_BOARDS: "/dashboard/board",
  DASHBOARD_BOARDS_CREATE: "/dashboard/board/create",
  DASHBOARD_BOARDS_EDIT: "/dashboard/board/edit",
  DASHBOARD_BOARDS_EDIT_BOARD: "/dashboard/board/edit-board",
  DASHBOARD_BOARDS_DELETE: "/dashboard/board/delete",
  DASHBOARD_POSTS: "/dashboard/posts",
  DASHBOARD_POSTS_CREATE: "/dashboard/posts/create",
  DASHBOARD_POSTS_EDIT: "/dashboard/posts/edit",
  DASHBOARD_POSTS_VIEW: "/dashboard/posts/view",
  DASHBOARD_POSTS_VOTERS: "/dashboard/posts/voters",
  DASHBOARD_POSTS_IMPORT: "/dashboard/posts/import",
  DASHBOARD_STATUS: "/dashboard/status",
  DASHBOARD_STATUS_ADD: "/dashboard/status/add",
  DASHBOARD_STATUS_EDIT: "/dashboard/status/edit",
  DASHBOARD_TAGS: "/dashboard/tags",
  DASHBOARD_TAGS_ADD: "/dashboard/tags/add",
  DASHBOARD_TAGS_EDIT: "/dashboard/tags/edit",
  DASHBOARD_TAGS_REPLACE: "/dashboard/tags/replace",
  DASHBOARD_USERS: "/dashboard/users",
  DASHBOARD_USERS_DETAILS: "/dashboard/users/details",
  DASHBOARD_CHANGELOG: "/dashboard/changelog",
  DASHBOARD_SETTINGS: "/dashboard/settings",
  DASHBOARD_INTEGRATION: "/dashboard/integration",
};

export default ROUTES;
